config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  devise_for :users

  resources :events
  resources :users, only: [:show]
  resources :participations


  get 'static_pages/index', to: 'static_pages#index'
  get 'static_pages/secret'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :user
  belongs_to :event   #participator class name User
  #belongs_to :administrator, class_name: "User"    #a ajouter peut etre

  after_create :participation

  def participation
    AttendanceMailer.participation(self.event.administrator, self.user).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord

  has_many :attendances
  has_many :users, through: :attendance

  belongs_to :administrator, class_name: "User"     #affaire à suivre

  validates :start_date, presence: true

  validates :duration, presence: true

  validates :title, presence: true
  validates :title, length: {minimum: 5, maximum: 140}

  validates :description, presence: true
  validates :description, length: {minimum: 20, maximum:1000}

  validates :price, numericality: {greater_tan: 0, less_than: 1001}
  validates :location, presence: true

  validate :multiple_of_5?

  validate :start_date_time


  def multiple_of_5?

    if self.duration != nil
      errors.add(:duration, "La duree doit etre un multiple de 5 !") unless
      self.duration % 5 == 0
    end

  end


  def start_date_time

    if self.start_date != nil
      errors.add(:start_date, "Tu ne peux pas créer un évènement dans le passé") unless
      self.start_date > Time.now
    end

  end

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendance

  validates :email, presence: true
  validates :email, uniqueness: true

  has_many :administrator_events, foreign_key: 'administrator_id', class_name: "Event", dependent: :destroy

  #envoyer les mails à la création de l'user

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, only: [:show, :new, :edit]

  def index

    @event = Event.all
    @attendance = Attendance.all

  end

  def new

    @event = current_user    #pour les alertes mais il y a un bugg inexpliquable, affaire a suivre
    @event = Event.new

  end

  def show

    @event = Event.find(params[:id])
    @attendance = Attendance

  end

  def create

    @event = Event.new(title: params[:title], location: params[:location], start_date: params[:start_date], duration: params[:duration], description: params[:description], price: params[:price], administrator_id: current_user.id )

    if @event.save
      flash[:success] = "Ton Evenement a été créé !"
      redirect_to events_path
    else
      flash.now[:danger] = "Ton evenement n'a pas été créé"
      render :new
    end

  end


  def edit

    @user = User.all
    @event = Event.find(params[:id])

  end


  def update

    @event = Event.find(params[:id])

      if @event.update(title: params[:title], location: params[:location], start_date: params[:start_date], duration: params[:duration], description: params[:description], price: params[:price], administrator_id: current_user.id )
        flash[:success] = "Ton event a été mis à jour"
        redirect_to user_path(current_user)
      else
        flash.now[:danger] = "Il y a eu un pb."
        render :edit
      end

  end


  def destroy

    @event = Event.find(params[:id])

    if @event.destroy
      flash[:success] = "Ton event a été supprimé"
      redirect_to user_path(current_user)
    else
      render :show
    end


  end

end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController


  def index


  end


  def new

    @event = Event.all

  end

  def edit


  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :authenticate_user!, only: [:secret]

  def index

  end

  def secret
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:show]

  def show

    @user = User.find(current_user.id)
    @userr = User.all
    @event = Event.where(administrator: current_user.id)

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
    <h1 style="text-align:center; margin-top:60px; margin-bottom:60px; color:#ED3833; font-size:38px;"> Tu peux y aller ! Balance les infos concernant ton Event ! !</h1>

<div style="background-color:#ED3833; opacity:70%; transform:skewY(-2deg); height:60em; margin-bottom:0px; ">
  <div class="container text-center py-4" style="transform:skewY(2deg);">


    <div style="text-align:center; margin-top:50px;">

    <%= form_tag url_for(action:'update'), method: "patch" do %>

      <p style="color:white; font-size:22px;"><strong><%= label_tag 'Titre de l évènement' %></strong><br></p>
      <%= text_field_tag 'title', @event.title  %>
      <br /> <br />

      <p style="color:white; font-size:22px;"><strong><%= label_tag 'Lieux' %></strong><br></p>
      <%= text_area_tag 'location', @event.location %>
      <br /> <br />

      <p style="color:white; font-size:22px;"><strong><%= label_tag 'Date de l évènement' %></strong><br></p>
      <%= text_area_tag 'start_date', @event.start_date %>
      <br /> <br />

      <p style="color:white; font-size:22px;"><strong><%= label_tag 'Durée' %></strong><br></p>
      <%= text_area_tag 'duration', @event.duration %>
      <br /> <br />

      <p style="color:white; font-size:22px;"><strong><%= label_tag 'Description' %></strong><br></p>
      <%= text_area_tag 'description', @event.description %>
      <br /> <br />

      <p style="color:white; font-size:22px;"><strong><%= label_tag 'Prix' %></strong><br></p>
      <%= text_area_tag 'price', @event.price %>
      <br /> <br />


      <%= submit_tag "Mettre à jour l'Event" %>

    <% end %>

    </div>
  </div>
</div>

app/views/events/index.html.erb
<div  class="jumbotron jumbotron-fluid" style="height:32em;">
  <div class="container">
    <!-- <h1 class="display-4" style="text-align:center; padding-top:80px; color:white;">Hello les MOUSS'</h1> -->
    <h1 class="ml11" style="text-align:center; color:white; font-size:68px; padding-top:80px;">
      <span class="text-wrapper">
        <span class="line line1"></span>
        <span class="letters">Bienvenue sur Event Bride !</span>
      </span>
    </h1>

<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

    <p style="text-align:center; font-size:28px; padding-top:40px; padding-bottom:40px; color:white;" class="lead"><strong>Tu pourras trouver ici tous les évènements qui auront lieu dans ta région.</strong></p>

  </div>
</div>



<h2 class="py-4"style="padding-left:120px;"> Voici tous la liste des prochains évènements à venir </h2>

<div class="card-columns container mx-auto">
  <% @event.each do |t| %>

    <center>
      <div class="card shadow" style="width: 20rem; padding-bottom:10px; border-color:#781D47;">
        <%= image_tag("#{["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg"].sample}", class: "card-img-top", size: "100x200") %>
        <!-- <img class="card-img-top" src="http://www.feteetcompagnie.fr/media//slidefetes__013340400_1443_18052016.jpg" alt="Card image cap"> -->
        <div class="card-body">
          <a style="color: #781D47; " class="card-title" href="<%=event_path(t)%>"> <%=t.title %></a>
          <p class="card-text"> Description : <%= t.description  %></p>
          <p class="card-text"> Prix : <%= t.price  %> €</p>
          <span class="card-text"><small class="text-muted"> Lieu : <%= t.location %></small></span><br>
          <span class="card-text"><small class="text-muted"> Date : <%= t.start_date %></small></span><br>
          <span class="card-text"><small class="text-muted"> Durée de l'évènement : <%= t.duration %> min.</small></span>
          <p></p>
          <% if user_signed_in? %>
          <button type="button" class="btn btn-outline-info">
            participants <span class="badge badge-light"><%= t.attendances.size %> </span>
          </button>
          <a style ="background-color:white; color:#ED3833; border-color:#ED3833;" class="btn btn-outline-light my-2 my-sm-0" href="<%=event_path(t)%>">Voir l'Event</a>
          <%end%>
        </div>
      </div>
      <br>
    </center>

  <%end %>
</div>


<style>

.jumbotron {
   background-image: url("https://cdn.pixabay.com/photo/2015/09/18/11/38/audience-945449_960_720.jpg");
    background-repeat: no-repeat;
    background-size:cover;
    background-attachment:fixed;
    height:30em;
  }


    .ml11 {
  font-weight: 700;
  font-size: 3.5em;
}

.ml11 .text-wrapper {
  position: relative;
  display: inline-block;
  padding-top: 0.1em;
  padding-right: 0.05em;
  padding-bottom: 0.15em;
}

.ml11 .line {
  opacity: 0;
  position: absolute;
  left: 0;
  height: 100%;
  width: 3px;
  background-color: #fff;
  transform-origin: 0 50%;
}

.ml11 .line1 {
  top: 0;
  left: 0;
}

.ml11 .letter {
  display: inline-block;
  line-height: 1em;


</style>



<script type="text/javascript">

  // Wrap every letter in a span
  var textWrapper = document.querySelector('.ml11 .letters');
  textWrapper.innerHTML = textWrapper.textContent.replace(/([^\x00-\x80]|\w)/g, "<span class='letter'>$&</span>");

  anime.timeline({loop: true})
    .add({
      targets: '.ml11 .line',
      scaleY: [0,1],
      opacity: [0.5,1],
      easing: "easeOutExpo",
      duration: 700
    })
    .add({
      targets: '.ml11 .line',
      translateX: [0, document.querySelector('.ml11 .letters').getBoundingClientRect().width + 10],
      easing: "easeOutExpo",
      duration: 700,
      delay: 100
    }).add({
      targets: '.ml11 .letter',
      opacity: [0,1],
      easing: "easeOutExpo",
      duration: 600,
      offset: '-=775',
      delay: (el, i) => 34 * (i+1)
    }).add({
      targets: '.ml11',
      opacity: 0,
      duration: 1000,
      easing: "easeOutExpo",
      delay: 1000
    });

</script>

app/views/events/new.html.erb
<% if @event.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p><strong>Nous n'avons pas réussi à créer votre profil pour la (ou les) raison(s) suivante(s) :</strong></p>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li ><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<style >
body {
  background-image: url("https://cdn.pixabay.com/photo/2016/06/02/02/33/triangles-1430105_960_720.png");
}

</style>


    <div class="container bg-white" style="margin-top:60px;">
        </br>
        <h1 class="display-4  mt-5 d-flex justify-content-center" style="color:#C73C3F;">Balance les infos concernant ton Event !</h1>
        <div class="container d-flex justify-content-center ">
          <div class="col-md-8 order-md-1">


            <%= form_tag url_for(action: 'create'), method: "post" do %>

                <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
                <br />

                <div class="mb-3">
                  <%= label_tag "Titre de l'évènement" %> </br>
                  <%= text_field_tag 'title', "", class: "form-control", placeholder: "Titre" %>
                </div>

                <div class="row">
                  <div class="col">
                    <%= label_tag 'La Date'%> </br>
                    <%= text_field_tag 'start_date', "", class: "form-control", placeholder: "2020-01-20 00:00:00"  %>
                  </div>
                  <br />
                  <div class="col">
                    <%= label_tag 'La durée ' %><span class="text-muted"> (en minutes svp)</span> </br>
                    <%= text_field_tag 'duration', "", class: "form-control"%>
                  </div>
                  <div class="col">
                    <%= label_tag 'Le prix ' %> <span class="text-muted"> (en €)</span> </br>
                    <%= text_field_tag 'price', "", class: "form-control"%>
                  </div>
                </div>
                </br>
                <div class="mb-3">
                  <%= label_tag "Le lieu" %> </br>
                  <%= text_field_tag 'location', "", class: "form-control", placeholder: "Montpellier"%>
                </div>

                <div class="mb-3">
                  <%= label_tag "Description de l'évènement " %><span class="text-muted"> (20 caractères min)</span> </br>
                  <%= text_area_tag 'description', "", class: "form-control"%>
                </div>

                <%= submit_tag "Valider", class: 'btn btn-primary btn-lg btn-block'  %>
                <br>
            <% end %>

          </div>
        </div>
    </div>

app/views/events/show.html.erb
<style>

.jumbotron {
  height: 360px;
  background-image: url("https://cdn.pixabay.com/photo/2015/03/26/10/22/band-691224_960_720.jpg");
  background-repeat: no-repeat;
  background-size:cover;
  background-attachment:fixed;
}

</style>


<div class="jumbotron jumbotron-fluid" >
  <div class="container">
    <h1 style="margin-top:100px; font-size:38px; color:white;" class="display-4"><strong>Tu trouveras ci-dessous toutes les infos qui t'intéresse pour l'évent </strong> <%= @event.title%></h1>
  </div>
</div>


<center>
<div class="card" style="width:60%;">
  <div class="card-header">
    <p><strong>Titre de l'évènement : </strong><%= @event.title%></p>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><strong>Description : </strong><%= @event.description%></p>
      <p><strong>Date de début : </strong><%= @event.start_date%></p>
      <p><strong>Date de fin : </strong><%= @event.start_date + @event.duration*60%></p>
      <footer class="blockquote-footer"><strong>Durée : <%= @event.duration %> min. </strong> <% @event.duration %>
      <cite title="Source Title"> Prix : <%= @event.price %> €<strong>
      <p> </p>
      <p><strong>Créateur de l'évènement : </strong><%= @event.administrator.email%></p>
      <p><strong>Nombre de participants : </strong><%=@attendance.where(user_id: @event.id).count%></p>
      <% if user_signed_in? %>
      <a style ="background-color:white; color:#ED3833; border-color:#ED3833;" class="btn btn-outline-light my-2 my-sm-0" href="<%= new_participation_path(@event.id) %>"> Participer !</a>
      <%end%>
    </blockquote>
  </div>
</div>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </head>

  <header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="<%= events_path %>">Event Brite</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="<%= new_event_path %>">Créer un Evènement <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <% if user_signed_in? %>
          <a style ="background-color:white; color:#ED3833; border-color:#ED3833;" class="btn btn-outline-light my-2 my-sm-0" href="<%=user_path(current_user)%>">Mon Profile</a>
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class:"btn btn-outline-light my-2 my-sm-0", style:"background-color:white; color:#9F221F; border-color:#9F221F;" %>
          <% else %>
          <a style ="background-color:white; color:#ED3833; border-color:#ED3833;" class="btn btn-outline-light my-2 my-sm-0" href="<%=new_user_session_path%>">Se Connecter</a>
          <a style ="background-color:#ED3833; color:white; border-color:#ED3833; " class="btn btn-outline-light my-2 my-sm-0" href="<%=new_user_registration_path%>">S'Inscrire</a>
          <%end%>
        </form>
      </div>
    </nav>

  </header>

  <body>

    <% if flash[:success] %>
      <div class="alert alert-success" role="alert">
        <div class="success text-center"><%= flash[:success]%></div>
      </div>
    <% elsif flash.now[:danger] %>
    <div class="alert alert-danger" role="alert">
      <div class="danger text-center"><%= flash.now[:danger]%></div>
    </div>
    <% else %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/participations/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/participations/new.html.erb
<p> kjkjkljlk </p>

<%= form_tag participations_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Prix : <%= @event.price %> </span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>

<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/users/show.html.erb
<style>

.jumbotron {
  height: 440px;
  background-image: url("https://cdn.pixabay.com/photo/2015/07/10/17/53/cheers-839865_960_720.jpg");
  background-repeat: no-repeat;
  background-size:cover;
  background-attachment:fixed;
}

</style>


<div class="jumbotron jumbotron-fluid" >
  <div class="container">
    <h1 style="margin-top:100px; font-size:78px; color:white;" class="display-4"><strong>Hello !</strong> <%= @user.first_name %></h1>
    <p style="font-size:48px; color:white;" class="lead">Voici ton profil perso à toi. Oui, à toi et rien qu'à toi !.</p>
  </div>
</div>



<% if current_user.id == @userr.find(params[:id]).id %>


<center>
      <div class="card shadow" style="width: 20rem; padding-bottom:10px; border-color:#781D47;">
        <img class="card-img-top" src="http://www.feteetcompagnie.fr/media//slidefetes__013340400_1443_18052016.jpg" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"> Prénom: <%= @user.first_name  %></p>
          <p class="card-text"> Nom : <%= @user.last_name  %></p>
          <p class="card-text"> Description : <%= @user.description  %></p>
          <p class="card-text"><small class="text-muted"> E-mail: <%= @user.email %></small></p>
          <%= link_to "Modifier mes Infos", edit_user_registration_path, class:"btn btn-outline-light my-2 my-sm-0", style:"background-color:white; color:#ED3833; border-color:#ED3833;" %>
        </div>
      </div>
      <br>
</center>


    <div class="jumbotron" style="height:280px;">
      <h2 class="display-4" style="color:white; font-size:60px; padding-left:120px; padding-top:40px;">Voici la liste des évènements que tu as créé !</h2>
    </div>


    <div class="card-columns container mx-auto">

    <% @event.each do |t| %>

        <center>
          <div class="card shadow" style="width: 20rem; padding-bottom:10px; border-color:#781D47;">
            <img class="card-img-top" src="http://www.feteetcompagnie.fr/media//slidefetes__013340400_1443_18052016.jpg" alt="Card image cap">
            <div class="card-body">
              <a style="color: #781D47; " class="card-title" href="<%=event_path(t)%>"> <%=t.title %></a>
              <p class="card-text"> Description : <%= t.description  %></p>
              <p class="card-text"> Prix : <%= t.price  %></p>
              <span class="card-text"><small class="text-muted"> Date de l'évènement: <%= t.start_date %></small></span><br>
              <span class="card-text"><small class="text-muted"> Durée de l'évènement: <%= t.duration %></small></span><br>
              <span class="card-text"><small class="text-muted"> Lieu : <%= t.location %></small></span><br><p></p>
              <a  href="<%=edit_event_path(t)%>" class="btn btn-outline-primary" > Modifier l'Event </a>
              <a href="<%=event_path(t)%>" class="btn btn-outline-danger" data-confirm="Êtes vous sûr de vouloir supprimer ce gossip?" data-method="DELETE">Supprimer</a>
            </div>
          </div>
          <br>
        </center>

      <%end %>
    </div>

<%else %> Déso, tu ne peux pas avori accès à cette page.
<%end %>